#!/usr/bin/env python3
"""Test a source-community richness gradient in exact-point seagrass insurance.

Frozen design: results/community_diversity_insurance_v1_contract.json

Consumes the already-defined community_insurance_transitions.csv generated by
analysis/34_community_insurance.py. No transition or target-state definition is changed.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

ROOT=Path(__file__).resolve().parents[1]
C=json.loads((ROOT/"results/community_diversity_insurance_v1_contract.json").read_text())
BOOT=int(C["implementation_freeze"]["bootstrap_replicates"])
SEED=int(C["implementation_freeze"]["random_seed"])
MIN_TRANS=int(C["hypothesis"]["minimum_transitions"])
MIN_NODES=int(C["hypothesis"]["minimum_nodes"])
MIN_LEVELS=int(C["hypothesis"]["minimum_distinct_richness_values"])


def richness(x)->int:
    return len({v for v in str(x).split(";") if v and v!="nan"})


def make_model():
    numeric=["source_alternative_richness","target_year"]
    categorical=["water_body"]
    pre=ColumnTransformer([
        ("num",StandardScaler(),numeric),
        ("cat",OneHotEncoder(handle_unknown="ignore"),categorical),
    ])
    return make_pipeline(
        pre,
        LogisticRegression(C=1.0,max_iter=2000,solver="lbfgs")
    )


def fit_coef(d:pd.DataFrame)->float:
    if d["target_any_seagrass_present"].nunique()<2:
        raise RuntimeError("one-class target in fit")
    model=make_model()
    cols=["source_alternative_richness","target_year","water_body"]
    model.fit(d[cols],d["target_any_seagrass_present"].astype(int))
    coef=float(model.named_steps["logisticregression"].coef_[0][0])
    return coef


def bootstrap(d:pd.DataFrame):
    nodes=sorted(d["node_id"].astype(str).unique())
    estimable=bool(
        len(d)>=MIN_TRANS
        and len(nodes)>=MIN_NODES
        and d["source_alternative_richness"].nunique()>=MIN_LEVELS
        and d["target_any_seagrass_present"].nunique()>=2
    )
    full_coef=fit_coef(d) if estimable else None
    out={
        "transitions":int(len(d)),
        "nodes":int(len(nodes)),
        "distinct_richness_values":int(d["source_alternative_richness"].nunique()),
        "observed_richness_values":sorted(int(x) for x in d["source_alternative_richness"].unique()),
        "standardized_richness_log_odds_coefficient":full_coef,
        "estimable":estimable,
    }
    if not estimable:
        out.update({"bootstrap_ci95":None,"supported":False,"bootstrap_replicates_used":0})
        return out

    by={n:d[d["node_id"].astype(str)==n] for n in nodes}
    rng=np.random.default_rng(SEED)
    vals=[]
    attempts=0
    while len(vals)<BOOT and attempts<BOOT*20:
        attempts+=1
        chosen=rng.choice(nodes,size=len(nodes),replace=True)
        dd=pd.concat([by[n] for n in chosen],ignore_index=True)
        if dd["target_any_seagrass_present"].nunique()<2:
            continue
        if dd["source_alternative_richness"].nunique()<2:
            continue
        try:
            vals.append(fit_coef(dd))
        except Exception:
            continue
    if len(vals)<BOOT:
        raise RuntimeError(f"insufficient valid bootstrap fits: {len(vals)}")
    arr=np.asarray(vals,float)
    ci=np.quantile(arr,[0.025,0.975])
    out.update({
        "bootstrap_ci95":[float(ci[0]),float(ci[1])],
        "supported":bool(ci[0]>0),
        "bootstrap_replicates_used":int(len(arr)),
    })
    return out


def descriptive_by_richness(d:pd.DataFrame):
    rows=[]
    for value,g in d.groupby("source_alternative_richness",sort=True):
        rows.append({
            "source_alternative_richness":int(value),
            "transitions":int(len(g)),
            "nodes":int(g["node_id"].nunique()),
            "target_occupied_events":int(g["target_any_seagrass_present"].sum()),
            "target_occupancy_fraction":float(g["target_any_seagrass_present"].mean()),
        })
    return pd.DataFrame(rows)


def marginal_predictions(d:pd.DataFrame):
    if d["target_any_seagrass_present"].nunique()<2:
        return pd.DataFrame()
    model=make_model()
    cols=["source_alternative_richness","target_year","water_body"]
    model.fit(d[cols],d["target_any_seagrass_present"].astype(int))
    rows=[]
    for value in sorted(int(x) for x in d["source_alternative_richness"].unique()):
        cf=d[cols].copy()
        cf["source_alternative_richness"]=value
        p=model.predict_proba(cf)[:,1]
        rows.append({
            "source_alternative_richness":int(value),
            "marginal_mean_predicted_target_occupancy":float(np.mean(p)),
        })
    return pd.DataFrame(rows)


def main(input_dir:Path,outdir:Path):
    outdir.mkdir(parents=True,exist_ok=True)
    trans=pd.read_csv(input_dir/"community_insurance_transitions.csv")
    required={
        "node_id","water_body","source_year","target_year",
        "source_alternative_species","target_any_seagrass_present"
    }
    missing=required.difference(trans.columns)
    if missing:
        raise RuntimeError(f"missing transition columns: {sorted(missing)}")

    d=trans.copy()
    d["source_alternative_richness"]=d["source_alternative_species"].fillna("").map(richness)
    d["target_any_seagrass_present"]=d["target_any_seagrass_present"].astype(bool)

    primary=bootstrap(d)
    desc=descriptive_by_richness(d)
    pred=marginal_predictions(d)

    result={
        "schema":"tampa.community_diversity_insurance_v1.result",
        "status":"completed_posthoc_exploratory",
        "contract":"results/community_diversity_insurance_v1_contract.json",
        "registry":{
            "transitions":int(len(d)),
            "nodes":int(d["node_id"].nunique()),
            "water_bodies":sorted(str(x) for x in d["water_body"].unique()),
            "target_year_range":[int(d["target_year"].min()),int(d["target_year"].max())],
        },
        "primary":primary,
        "descriptive_by_richness":desc.to_dict("records"),
        "marginal_predictions":pred.to_dict("records"),
        "interpretation":(
            "A positive supported richness coefficient would extend binary source-mixture insurance to a diversity gradient: exact points with more alternative seagrass taxa before Thalassia loss would be more likely to remain seagrass-occupied afterward."
        ),
        "claim_boundary":C["claim_boundary"],
    }

    d.to_csv(outdir/"community_diversity_insurance_transitions.csv",index=False)
    desc.to_csv(outdir/"community_diversity_insurance_by_richness.csv",index=False)
    pred.to_csv(outdir/"community_diversity_insurance_marginal_predictions.csv",index=False)
    (outdir/"community_diversity_insurance_v1.json").write_text(
        json.dumps(result,indent=2,sort_keys=True)+"\n"
    )
    print(json.dumps(result,indent=2,sort_keys=True))


if __name__=="__main__":
    p=argparse.ArgumentParser()
    p.add_argument("--input",type=Path,default=Path("results/generated_diversity_insurance"))
    p.add_argument("--out",type=Path,default=Path("results/generated_diversity_insurance"))
    a=p.parse_args()
    main(a.input,a.out)
